#!/bin/bash
if [ "$4" = "S" ]; then
  python3 client_sender.py $2 $6 $8 ${10} ${12}
elif [ "$4" = "R" ]; then
  python3 client_receiver.py $2 $6 $8 ${10} ${12}
 fi

# ./client -n alice -m S -o bob -i plaintext -a 127.0.0.1 -p 12345
# ./client -n bob -m R -s outenc.txt -o outfile.txt -a 127.0.0.1 -p 12345
